version: '3.3'

services:
  db:
    image: git-registry.gibb.ch/rfe140502/m169sf/images/mysql:5.7
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: sml12345
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: sml12345

  wordpress:
    depends_on:
      - db
    image: git-registry.gibb.ch/rfe140502/m169sf/images/wordpress:latest
    ports:
      - "8000:80"
    restart: always
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: sml12345
      WORDPRESS_DB_NAME: wordpress
volumes:
  db_data:
